version: '3'
   
services:
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # 外部アクセスをポート80で受け取る
    #volumes:
    #  - ./nginx.conf:/etc/nginx/nginx.conf:ro  # カスタムNginx設定ファイル
    #depends_on:
    #s  - grafana
    restart: unless-stopped

networks:
  ecosystem:
    external: true  # 既に作成されたネットワークを使用する場合